(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var d="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},g=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},h=g(this),aa=function(a,b){if(b){var c=h;a=a.split(".");for(var e=0;e<a.length-
1;e++){var f=a[e];f in c||(c[f]={});c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&d(c,a,{configurable:!0,writable:!0,value:b})}};aa("Array.from",function(a){return a?a:function(b,c,e){c=null!=c?c:function(ba){return ba};var f=[],l="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof l){b=l.call(b);for(var m=0;!(l=b.next()).done;)f.push(c.call(e,l.value,m++))}else for(l=b.length,m=0;m<l;m++)f.push(c.call(e,b[m],m));return f}});
var k=this||self,ca=/^[\w+/_-]+[=]{0,2}$/,n=null,p=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ca.test(a)?a:""};var da=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,e="string"===typeof a?a.split(""):a,f=0;f<c;f++)if(f in e&&b.call(void 0,e[f],f,a))return!0;return!1};var t=function(a,b){this.f=a===q&&b||"";this.c=r},r={},q={};var u;a:{var v=k.navigator;if(v){var w=v.userAgent;if(w){u=w;break a}}u=""};var x=function(a,b){if(!ea()){var c=Math.random();if(c<b)return c=fa(),a[Math.floor(c*a.length)]}return null},fa=function(){if(!k.crypto)return Math.random();try{var a=new Uint32Array(1);k.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},ea=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return da(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],ha)||1E-4>Math.random()}),ha=function(a){return-1!=u.indexOf(a)};var ia=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(e){}return!0}(k,!1)?"https:":"http:";var y={j:1,h:4,i:5,g:7},z={b:"40004006",a:"40004007"};function ja(){return{1:.5,4:.02,5:.001,7:0}}function ka(){var a=A,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;for(var c in y)if(b=a[y[c]],"number"!==typeof b||0>b||1<b)return!1;return!0};function la(){var a=k.dcmads;return null!=a.eids?a.eids:"complete"!==k.document.readyState?"":(a=x([z.b,z.a],a.expts[4]))?"4|"+a:""};try{k.dcmads=k.dcmads||{};k.dcmads.startTime=(new Date).getTime();var ma=k.dcmads,B=k.dcmads.version,C={loader:157};if(B)if(C.experiment=B.experiment,57==B.number||"p"==B.number)C.number=57;else if(57==B.number||"c"==B.number)C.number=57;if(!C.number){var D=x([57,57],0);C.experiment=!!D;C.number=D||57}ma.version=C;var na=k.dcmads,E,A=k.dcmads.expts,F;F=void 0===F?ja:F;E=ka()?A:F();na.expts=E;k.dcmads.eids=la();var oa="4|"+z.a,G,H=k.dcmads.version,I=H.number,J="";H.experiment&&57==I&&(J="?rxp=57x57");
var pa="impl_v"+I+".js"+J,K=k.document,L=K.currentScript||Array.from(K.getElementsByTagName("script")).pop();G=(0==(L&&L.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+pa;if(k.dcmads.eids===oa){var M=k.document,N=M.createElement("script"),O=new t(q,G);N.src=O instanceof t&&O.constructor===t&&O.c===r?O.f:"type_error:TrustedResourceUrl";var P;var Q=N.ownerDocument&&N.ownerDocument.defaultView;Q&&Q!=k?P=p(Q.document):(null===n&&(n=p(k.document)),P=n);P&&N.setAttribute("nonce",
P);var R=M.getElementsByTagName("script")[0];R&&R.parentNode&&R.parentNode.insertBefore(N,R)}else k.document.write('<script src="'+G+'">\x3c/script>')}catch(a){if(.01>Math.random()){var S="";try{var T,U=a.toString();a.name&&-1==U.indexOf(a.name)&&(U+=": "+a.name);a.message&&-1==U.indexOf(a.message)&&(U+=": "+a.message);if(a.stack){var V=a.stack,W=U;try{-1==V.indexOf(W)&&(V=W+"\n"+V);for(var X;V!=X;)X=V,V=V.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");U=V.replace(/\n */g,"\n")}catch(b){U=
W}}T=U;T=T.substring(0,1024);S=encodeURIComponent(T)}catch(b){S="extr"}var Y=k.dcmads.eids,Z=document.createElement("img");Z.src=ia+"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=157&context=554"+((Y?"&eids="+Y:"")+"&msg="+S);(k.google_image_requests=k.google_image_requests||[]).push(Z)}};}).call(this);
